{% set name = "wakepy" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wakepy-{{ version }}.tar.gz
  sha256: a9425e8e77e89bccfe24a70f33ecd8596b474c75ddac79310cd54f2bc92210e3

build:
  noarch: python
  entry_points:
    - wakepy = wakepy.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==69.1.0
    - setuptools-scm ==8.1.0
    - pip
  run:
    - python >={{ python_min }}
    - jeepney >=0.7.1
    - typing-extensions

test:
  imports:
    - wakepy
  commands:
    - pip check
    - wakepy --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fohrloop/wakepy
  summary: Cross-platform keep-awake with python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fohrloop
    - thewchan
