{% set name = "wakepy" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wakepy-{{ version }}.tar.gz
  sha256: 4e7e820512e0e69f9aa5fdded2d3225e6f7c9f000814300e8c37d1fa88fe1664

build:
  noarch: python
  entry_points:
    - wakepy = wakepy.__main__:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools ==69.1.0
    - setuptools-scm ==8.1.0
    - pip
  run:
    - python >=3.7
    - jeepney >=0.7.1
    - typing-extensions

test:
  imports:
    - wakepy
  commands:
    - pip check
    - wakepy --help
  requires:
    - pip

about:
  home: https://github.com/fohrloop/wakepy
  summary: Cross-platform keep-awake with python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
